version: "3.3"
services:
  angular_backend:
    container_name: "angular_backend"
    expose:
     - "4200"
    ports:
     - "4200:4200"
    build: .
    command: ng serve --host 0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
